--- #YAML:1.0
name:                HTML-WikiConverter-GoogleCode
version:             0.11
abstract:            Convert HTML to Google Code wiki markup.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    HTML::WikiConverter:           0.61
    Params::Validate:              0
    Test::More:                    0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Marty Kube <martykube@yahoo.com>
